### ISSUE TITLE
好久没写过 Original JavaScript 了，这些年用 Vue 操作 Dom 都习惯了，很好 Mark 一下。

### ISSUE THREAD

**Issue by WhaleFell** [Moemu/FortuneUpUp#1]
提个建议哈，可以用上一些前端框架实现一些动画和自适应手机端功能，比如 jQuery、layui、bootstrap 之类的。

熟练了直接上 Vue 自己写组件，CSS 用 less 写。

不过初学前端，多写写一些原生的 JavaScript ，用原生 JavaScript 操作 Dom 也是有很必要的，加油！

**Comment by Moemu** [comment]
确实，里面的功能确实有些用jQuery等这些框架会更加便捷，不过考虑到自己阅历有限，就没有为难自己上框架。
您的建议咱会记在心上，感谢您的关注~
